<?PHP
//Dies Stellt den Header dar !!
?>


<html>
<head>
<title><?PHP echo $PageName; ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body bgcolor="#FFFFFF" text="#000000">
<p> 
  
</p>
<p>&nbsp;</p>
<hr>
<table width="100%" border="0" cellspacing="5" cellpadding="10">
  <tr> 
    <td bgcolor="#CCCCCC" width="30%" nowrap valign="top">
      <div align="center"><u>Menü</u></div><br>
      <div align="center"><a href="test.php">Notiz erstellen</a></div><br>
      <div align="center"><a href="test1.php">Notiz erstellen</a></div><br>
      <div align="center"><a href="test2.php">Notiz erstellen</a></div><br>
    </td>
    <td width="70%" nowrap>